name: mysql-server # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '8.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: MySQL server in a snap. # 79 char long summary
description: |
  The MySQL software delivers a very fast, multithreaded, multi-user, 
  and robust SQL (Structured Query Language) database server. MySQL 
  Server is intended for mission-critical, heavy-load production 
  systems as well as for embedding into mass-deployed software.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  mysql:
    command: usr/bin/mysql
  mysql-config-editor:
    command: usr/bin/mysql_config_editor
  mysqldump:
    command: usr/bin/mysqldump
  mysqlpump:
    command: usr/bin/mysqlpump
  mysqlslap:
    command: usr/bin/mysqlslap
  mysqladmin:
    command: usr/bin/mysqladmin
  mysqld:
    command: usr/sbin/mysqld
    daemon: simple
  mysqldumpslow:
    command: usr/bin/mysqldumpslow
  mysqlrepair:
    command: usr/bin/mysqlrepair
  mysql-ssl-rsa-setup:
    command: usr/bin/mysql_ssl_rsa_setup
  mysqlanalyze:
    command: usr/bin/mysqlanalyze
  mysqlimport:
    command: usr/bin/mysqlimport
  mysqlreport:
    command: usr/bin/mysqlreport
  mysql-tzinfo-to-sql:
    command: usr/bin/mysql_tzinfo_to_sql
  mysqlbinlog:
    command: usr/bin/mysqlbinlog
  mysql-migrate-keyring:
    command: usr/bin/mysql_migrate_keyring
  mysql-secure-installation:
    command: usr/bin/mysql_secure_installation
  mysql-upgrade:
    command: usr/bin/mysql_upgrade
  mysqlcheck:
    command: usr/bin/mysqlcheck
  mysqloptimize:
    command: usr/bin/mysqloptimize
  myslqshow:
    command: usr/bin/mysqlshow

parts:
  mysql-server-deb:
    plugin: nil
    build-packages:
      - mysql-server-8.0
    stage-packages:
      - mysql-server-8.0
    override-build: |
      cp -r /var/lib/mysql* $CRAFT_PART_INSTALL/var/lib/
    override-stage: |
      echo "stage"
